name: Test Reports

on:
  workflow_run:
    workflows: [ CI ]
    types:
      - completed

permissions:
  contents: read
  actions: read
  checks: write

jobs:
  report:
    runs-on: ubuntu-latest

    steps:
      - uses: dorny/test-reporter@v3
        with:
          artifact: test-results
          name: Unit Tests
          path: '**/*.xml'
          reporter: java-junit